MP=mp.bin
SOURCES=$(wildcard *.c)

all: $(MP)

$(MP): $(SOURCES)
	echo "If this fails on cygwin, try uncommenting the -largp flag"; 

	gcc $(SOURCES) -o $(MP) 




clean:
	rm -rf $(MP)

.PHONY: all clean
